### ISSUE TITLE
有哪位大佬能用java写一遍吗

### ISSUE THREAD

**Issue by wangdabin2333** [angcyo/DslAdapter#1]
来个大佬用java翻一遍。

**Comment by angcyo** [comment]
什么年代了, 还写`Java`.

赶紧学`Kotlin`.

**Comment by W252016021** [comment]
> 什么年代了, 还写`Java`.
> 
> 赶紧学`Kotlin`.

辣鸡，都不支持java，tui~~

**Comment by simplepeng** [comment]
垃圾，我要java版本

**Comment by simplepeng** [comment]
🌶🐔，我要java，我要java

**Comment by angcyo** [comment]
`Java`是实现不了的.
这是`kotlin`的特性.
