### ISSUE TITLE
关于群组功能问题

### ISSUE THREAD

**Issue by lijinshanmx** [angcyo/DslAdapter#10]
正常代码如下:
 
<img width="855" alt="截屏2021-06-25 12 05 34" src="https://user-images.githubusercontent.com/6552340/123368106-c1a7f300-d5ad-11eb-8d95-7260367ee44e.png">

demo中 使用的是 DslDemoItem即 DslAdapterItem的子类。这里为了简便直接使用内部类了。

错误代码如下:

<img width="738" alt="截屏2021-06-25 12 07 47" src="https://user-images.githubusercontent.com/6552340/123368248-02077100-d5ae-11eb-8e93-2c705b7c186f.png">

这里直接使用 DslAdapterItem类型，然后itemGroups已正常填写，此时展开折叠的时候，会出现其他头部也显示隐藏的问题，感觉头部item和正常item混淆了。

错误示例录屏如下:

https://user-images.githubusercontent.com/6552340/123368402-57dc1900-d5ae-11eb-90bc-27db803b4082.mp4

**Comment by lijinshanmx** [comment]
是我itemGroups使用错误还是这块代码逻辑判断有遗漏呢？

<img width="858" alt="截屏2021-06-25 12 11 54" src="https://user-images.githubusercontent.com/6552340/123368580-a2f62c00-d5ae-11eb-8bd0-0bfc9f191f2f.png">

希望作者指点一下哈~

**Comment by angcyo** [comment]
最新`master`分支代码, 测试正常.

![image](https://user-images.githubusercontent.com/6269676/123725856-6f264980-d8c1-11eb-9103-79d4bda4f42a.png)

---

`isItemInGroups`是库中执行分组功能的默认实现, 可以覆盖自定义的分组实现.

`itemGroups`用于快速进行相同分组名之间的分组实现. 及于`isItemInGroups`实现的.

**Comment by lijinshanmx** [comment]
<img width="1479" alt="截屏2021-06-29 10 27 17" src="https://user-images.githubusercontent.com/6552340/123727776-c2e66200-d8c4-11eb-9cf3-68b5931377f2.png">

你在 GroupDemoActivity.kt 里面 按照我上图的修改，然后试下，点击折叠展开时会有问题，头部会闪动。

**Comment by lijinshanmx** [comment]
61行设置 dslItem(R.layout.item_demo_list) 错误，录屏如下:

https://user-images.githubusercontent.com/6552340/123728070-4c962f80-d8c5-11eb-878a-b3682edaa24b.mp4

61行 设置    dslItem(DslDemoItem())  正常，录屏如下:

https://user-images.githubusercontent.com/6552340/123728101-59b31e80-d8c5-11eb-89d3-8efbda996318.mp4

两者的不同之处在于， DslDemoItem 是DslAdapterItem的子类，而直接传入R.layout.item_demo_list则是DslAdapterItem 类本身。
所以，我现在代码里的兼容方案是 群组子Item 我都是单独在创建一个新的DslAdapterItem子类（就是仿照demo里面的示例，用的是DslDemoItem），就不会出现这个问题了，但是我觉得能解决掉是最好的了。

**Comment by angcyo** [comment]
感谢反馈.

这是`thisAreItemsTheSame`默认实现判断不符合场景导致, 

`2.6.3`已调整了实现逻辑, 满足了此场景.
