### ISSUE TITLE
clearAllItems等清除功能不起作用

### ISSUE THREAD

**Issue by monakatyking** [angcyo/DslAdapter#16]
用一个adapter通过addLastItem切换两种不同的样式，且两个样式的数据也不一样
再切换的时候尝试过单独或同时使用clearAllItems，updateItemDepend，_updateAdapterItems，notifyDataSetChanged，notifyDataSetChanged，皆不能清除
请问除了每个样式用单独的adapter外，有没有什么办法可以用一个adapte，切换的时候清除数据后在插入新的item

**Comment by angcyo** [comment]
不同样式的`item`, 声明成2个类, 且对应`item`的`itemLayoutId`用不同的`xml`布局文件.

先调用`clearAllItems`, 清除原有的`item`,
之后调用`addLastItem`, 添加新的`item`.

**Comment by monakatyking** [comment]
切换的时候好像有延迟，而且有时候还是不起作用
举个例子，有a,b两个不同的item类，他们的itemdata也不一样，a有数据调用addLastItem加载成功，切换到b的时候，b没有数据，调用clearAllItems，第一次清除成功，切换到a，先调用clearAllItems,之后调用addLastItem加载成功，再切换到b的时候由于b没有数据，仅调用clearAllItems，a的item并没有清除
切换是用的DslTabLayout

**Comment by angcyo** [comment]
`clearAllItems`后, 要调用`updateItemDepend`才会通知更新界面. 否则只是清除了`allItems`数据, 并没有清除界面.

**Comment by monakatyking** [comment]
还是有抖动的情况
Duplicate of #

https://user-images.githubusercontent.com/18531851/131972321-4ab7b476-d59c-4e9e-b7af-74e9a3f76362.mp4

**Comment by monakatyking** [comment]
clearAllItems后, 要调用updateItemDepend，还是有抖动的情况，而且当使用tabLayout.setCurrentItem，当点击item的时候跳转，数据有时候也没有清空




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "angcyo/DslAdapter"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月3日(星期五) 下午2:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [angcyo/DslAdapter] clearAllItems等清除功能不起作用 (#16)





 
clearAllItems后, 要调用updateItemDepend才会通知更新界面. 否则只是清除了allItems数据, 并没有清除界面.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by angcyo** [comment]
默认是异步计算`Diff`, 可以通过`updateNow`进行同步操作.

**Comment by monakatyking** [comment]
请问updateNow在什么时候调用，是在clearAllItems后么？
试过clearAllItems，updateItemDepend，updateNow，试过clearAllItems，updateNow，试过clearAllItems，updateNow，updateItemDepend
截屏的播放好像加速了，实际看的时候抖的更明显些




------------------ 原始邮件 ------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月5日(星期天) 上午10:41
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [angcyo/DslAdapter] clearAllItems等清除功能不起作用 (#16)





 
默认是异步计算Diff, 可以通过updateNow进行同步操作.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by angcyo** [comment]
你试试把`RecyclerView`的`ItemAnimator`置空.

**Comment by monakatyking** [comment]
终于好了，万分感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月6日(星期一) 上午9:44
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [angcyo/DslAdapter] clearAllItems等清除功能不起作用 (#16)





 
你试试把RecyclerView的ItemAnimator置空.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by monakatyking** [comment]
请问updateNow在什么时候调用，是在clearAllItems后么？
试过clearAllItems，updateItemDepend，updateNow，试过clearAllItems，updateNow，试过clearAllItems，updateNow，updateItemDepend
截屏的播放好像加速了，实际看的时候抖的更明显些




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月5日(星期天) 上午10:41
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [angcyo/DslAdapter] clearAllItems等清除功能不起作用 (#16)





 
默认是异步计算Diff, 可以通过updateNow进行同步操作.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by angcyo** [comment]
> 请问updateNow在什么时候调用，是在clearAllItems后么？ 试过clearAllItems，updateItemDepend，updateNow，试过clearAllItems，updateNow，试过clearAllItems，updateNow，updateItemDepend 截屏的播放好像加速了，实际看的时候抖的更明显些
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2021年9月5日(星期天) 上午10:41 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [angcyo/DslAdapter] clearAllItems等清除功能不起作用 (#16) 默认是异步计算Diff, 可以通过updateNow进行同步操作. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

操作完所有`item`后, 调用`updateNow`可以立即触发界面更新.
