### ISSUE TITLE
支持上下Item流的逻辑关联

### ISSUE THREAD

**Issue by Alanqiu** [angcyo/DslAdapter#18]
这个样式demo 支持吗？没看到相关代码

**Comment by angcyo** [comment]
好的，稍后补充demo代码。

**Comment by Alanqiu** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。

**Comment by angcyo** [comment]
demo已更新.

`com.angcyo.dsladapter.dsl.DslUpdateParentItem`
`com.angcyo.dsladapter.dsl.DslUpdateChildItem`

**Comment by Alanqiu** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。
