### ISSUE TITLE
排序相关

### ISSUE THREAD

**Issue by vistar1986** [angcyo/DslAdapter#20]
如何使用该库实现自动排序功能？我以前使用的是SortedList库进行排序的，现在改用了DslAdapter之后只能暴力更新了
val list = dslAdapter.dataItems.map { it as DailyPlanItem }
                val cache2 = list.filter { it.nonData() }
                val cache1 =
                    list.filter { !it.nonData() }
                        .sortedBy { it.info.timeString }
                        .toMutableList()
                cache1.apply { addAll(cache2) }

                renderAdapter {
                    updateItem("${it.itemTag}")
                    resetItem(cache1)
                }

**Comment by angcyo** [comment]
对真实数据进行排序, 然后丢给`item`显示, 并不需要对`item`进行排序. 对`Item`的排序没有意义.
