### ISSUE TITLE
折叠+单选，折叠后无法及时更新

### ISSUE THREAD

**Issue by zhangxu2814** [angcyo/DslAdapter#23]
群组状态下：
1.选中组内某条数据
2.折叠这个群组
3.选中其他组内的数据
4.展开所有折叠的群组 发现有两条选中的状态

https://user-images.githubusercontent.com/8907295/188773132-d44b0c96-96c8-4799-9598-a4c7c7657056.mp4

**Comment by angcyo** [comment]
你是怎么控制`选中`状态的?

**Comment by zhangxu2814** [comment]
updateItemSelector(!itemIsSelected)

**Comment by zhangxu2814** [comment]
class GroupDemoActivity : BaseRecyclerActivity() {

    override fun onInitBaseLayoutAfter() {
        super.onInitBaseLayoutAfter()
        recyclerView.setPadding(10 * dpi, 0, 10 * dpi, 0)
        dslAdapter.render {
            setAdapterStatus(DslAdapterStatusItem.ADAPTER_STATUS_LOADING)
            itemSelectorHelper.selectorModel = ItemSelectorHelper.MODEL_SINGLE
        }
        dslViewHolder.postDelay(1000) {
            renderAdapter {
                setAdapterStatus(DslAdapterStatusItem.ADAPTER_STATUS_NONE)
                for (i in 0..Random.nextInt(2, 3)) {
                    dslItem(R.layout.item_group_head) {
                        itemIsGroupHead = true //启动分组折叠
                        itemIsHover = false //关闭悬停
                        itemGroups = mutableListOf("group${i + 1}")
                        itemTopInsert = 10 * dpi
                        itemBindOverride = { itemHolder, itemPosition, adapterItem, _ ->
                            itemHolder.tv(R.id.fold_button)?.text =
                                if (itemGroupExtend) "折叠 $itemPosition" else "展开 $itemPosition"
                            itemHolder.tv(R.id.text_view)?.text = "分组${i + 1}"
                            itemHolder.click(R.id.fold_button) {
                                itemGroupExtend = !itemGroupExtend
                            }
                            itemGroupParams.apply {
                                if (isOnlyOne()) {
                                    itemHolder.itemView
                                        .setBackgroundResource(R.drawable.shape_group_all)
                                } else if (isFirstPosition()) {
                                    itemHolder.itemView
                                        .setBackgroundResource(R.drawable.shape_group_header)
                                } else {
                                    itemHolder.itemView
                                        .setBackgroundColor(resources.getColor(R.color.colorAccent))
                                }
                            }
                        }
                    }
                    for (j in 0..Random.nextInt(2, 3)) {
                        dslItem(DslDemoItem()) {
                            itemGroups = mutableListOf("group${i + 1}")
                            itemText = "我是第${i + 1}组的第 $j 条数据"
                            itemBindOverride = { itemHolder, itemPosition, _, _ ->
                                itemHolder.v<TextView>(R.id.text_view)?.setBackgroundColor(
                                    when {
                                        itemIsSelected -> Color.GREEN
                                        else -> Color.WHITE
                                    }
                                )
                                itemGroupParams.apply {
                                    if (isLastPosition()) {
                                        itemHolder.itemView
                                            .setBackgroundResource(R.drawable.shape_group_footer)
                                    } else {
                                        itemHolder.itemView
                                            .setBackgroundColor(resources.getColor(R.color.default_base_white))
                                    }
                                }
                            }
                            itemClick = {
                                updateItemSelector(!itemIsSelected)
                            }
                        }
                    }
                }
            }
        }
    }
}

**Comment by angcyo** [comment]
你可以扩展`DslAdapterItem`提供一个方法:

```
/**更新选项*/
open fun updateItemSelector(
    select: Boolean,
    selectorParams: SelectorParams = SelectorParams(
        this,
        select.toSelectOption(),
        _useFilterList = false
    )
) {
    itemDslAdapter?.itemSelectorHelper?.selector(selectorParams)
}
```
注意参数`_useFilterList=false`即可.

**Comment by zhangxu2814** [comment]
> 你可以扩展`DslAdapterItem`提供一个方法:
> 
> ```
> /**更新选项*/
> open fun updateItemSelector(
>     select: Boolean,
>     selectorParams: SelectorParams = SelectorParams(
>         this,
>         select.toSelectOption(),
>         _useFilterList = false
>     )
> ) {
>     itemDslAdapter?.itemSelectorHelper?.selector(selectorParams)
> }
> ```
> 
> 注意参数`_useFilterList=false`即可.
感谢 已解决
