### ISSUE TITLE
树结构+单选，折叠后无法及时更新

### ISSUE THREAD

**Issue by zhangxu2814** [angcyo/DslAdapter#24]
已参考 ，群组折叠+单选的修改方式。

> https://github.com/angcyo/DslAdapter/issues/23#issue-1363995206
数结构时 _useFilterList = false 时获取不到所有的数据

https://user-images.githubusercontent.com/8907295/188847523-f2b43607-1f4a-4c2f-a5c5-1bd3f86b5cb3.mp4

**Comment by angcyo** [comment]
`5.1.1`你试试.

**Comment by zhangxu2814** [comment]
感谢，没成功。我看明白原理了。我这属于多层嵌套，一遍for取不尽。

**Comment by zhangxu2814** [comment]
private fun selectorSublist(allItems: List<DslAdapterItem>, item: DslAdapterItem?) {
        allItems.forEach {
            if (it.itemSubList.isNullOrEmpty()) {//证明是最子层，或者没子层
                if (it.itemIsSelected && it != item) {
                    if (it.isItemCanSelected(it.itemIsSelected, false)) {
                        _selectorInner(
                            SelectorParams(
                                it,
                                selector = OPTION_DESELECT,
                                notifySelectListener = true
                            )
                        )
                    }
                }
            } else {//中间层，继续往下查
                selectorSublist(it.itemSubList, item)
            }
        }
    }

**Comment by angcyo** [comment]
`5.1.2`试试. 加了递归!

**Comment by zhangxu2814** [comment]
产生了一个新的问题。 当子布局被选中时并且他的父布局被折叠，会导致取不到这个被折叠的选中状态。看过代码的逻辑，建议   1. _updateAdapterItems 方法的  adapterItems.addAll(dataItems) 部分，将所有的子类放进adapterItems中。2.ItemSelectorHelper中所有关于选择的方法不进行过滤。
3.回退今天修改的方法，并改为不过滤
<img width="837" alt="image" src="https://user-images.githubusercontent.com/8907295/189114079-f72e7df2-a28d-414c-8639-d38b855f2a72.png">

**Comment by angcyo** [comment]
新增了一个新的api `com.angcyo.dsladapter.DslAdapter#getDataAndSubList`
