### ISSUE TITLE
addLastItem 问题

### ISSUE THREAD

**Issue by YQcharlse** [angcyo/DslAdapter#26]
老哥，在界面初始化时，通过addLastItem加载DslAdapterItem集合，item会出现堆积在一起后再按顺序显示的情况，这个怎么才能优化下呢？

**Comment by angcyo** [comment]
提供一下复现的`demo`源代码?

**Comment by YQcharlse** [comment]
刚试试了下通过
  monitorListItem.render {
          item()(){}
        }
这种方法也是会有，视图出现时也是会有堆积
不好意思老哥，我的item比较复杂不太容易复现demo， item里还有嵌套有RecyclerView是否是这个问题

**Comment by angcyo** [comment]
库用的是哪个版本?是否是最新版`5.2.0`?

**Comment by YQcharlse** [comment]
嗯嗯是的

**Comment by angcyo** [comment]
检查一下, 是否有死循环在短时间内频繁调用了`render`方法.

**Comment by YQcharlse** [comment]
没有频繁调用， 是我先初始化了render 了界面，然后才获取到数据给item显示内容，应该是因为这样
