### ISSUE TITLE
view must have a tag

### ISSUE THREAD

**Issue by Czdzdz** [angcyo/DslAdapter#27]
override fun onItemBind(
itemHolder: DslViewHolder,
itemPosition: Int,
adapterItem: DslAdapterItem,
payloads: List
) {
    super.onItemBind(itemHolder, itemPosition, adapterItem, payloads)
    ItemViewBindingItemBinding.bind(itemHolder.itemView).apply{
          ...
        }
}

**Comment by Czdzdz** [comment]
var itemViewBindingItemBinding: ItemViewBindingItemBinding? = null
override fun onItemBind(
        itemHolder: DslViewHolder,
        itemPosition: Int,
        adapterItem: DslAdapterItem,
        payloads: List<Any>
    ) {
        super.onItemBind(itemHolder, itemPosition, adapterItem, payloads)
itemViewBindingItemBinding = itemViewBindingItemBinding ?: ItemViewBindingItemBinding.bind(itemHolder.itemView)

    databinding.bind(itemHolder.itemView).apply{
    ...
    }
}

**Comment by angcyo** [comment]
DataBinding is not currently supported.

**Comment by Czdzdz** [comment]
thanks for your reply



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年12月5日(星期一) 下午2:58
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [angcyo/DslAdapter] view must have a tag (Issue #27)





 
DataBinding is not currently supported.

**Comment by angcyo** [comment]
have fun
