### ISSUE TITLE
分页加载

### ISSUE THREAD

**Issue by 10433yx** [angcyo/DslAdapter#28]
请问我是复杂的组布局想要实现翻页加载，怎么实现比较好呢?addLastItem总是直接就滚动到最后了，而且数据直接错位插到原来的数据里，updateSingleData是限定了item类型，希望能有更多常见场景的示例，能够更好上手啊

**Comment by 10433yx** [comment]
分页加载，不希望直接就加载出来就蹦到最末尾了啊，

**Comment by angcyo** [comment]
不知道从什么方向帮助您~

**Comment by 10433yx** [comment]
override fun loadMoreDealDetailListSuccess(dealDetailListBean: DealDetailListBean) {
        dslAdapter.render {
            for (u in dealDetailListBean.list) {
                var currentTime = TimeStampUtil.transToChineseStringYearMonth(u.create_time)
                if (currentTime != time) {
                    dslAdapter.dslItem(
                        DslDealDetialListGroupItem(
                            this@DealDetailListActivity, u
                        )
                    )
                    time = currentTime
                }
                dslAdapter.dslItem(
                    DslDealDetialListContentItem(
                        this@DealDetailListActivity, u
                    )
                )

            }
        }
    }

上拉加载获取数据后这么写，它每次刷新后直接蹦到当前加了新数据的列表最后了。只想追加数据，不想列表滚动，用户都找不到刚才刷到哪了，这是一个带2种布局的列表

**Comment by angcyo** [comment]
`diff`操作, 需要满足以下2个方法, 才能正确渲染.
```
com.angcyo.dsladapter.DslAdapterItem#areItemsTheSame
com.angcyo.dsladapter.DslAdapterItem#areContentsTheSame
```

你可以尝试将`DslDealDetialListContentItem.itemData`属性赋值.

**Comment by 10433yx** [comment]
> itemData

管用了！非常感谢！
