### ISSUE TITLE
只有最新版本了吗

### ISSUE THREAD

**Issue by wsdydeni** [angcyo/DslAdapter#29]

**Comment by angcyo** [comment]
老版本下载不了, 可能是jitpack的问题!

**Comment by wsdydeni** [comment]
> 老版本下载不了, 可能是jitpack的问题!

能说这个库真的没有完整教程吗，详细使用wiki。。。

**Comment by angcyo** [comment]
> > 老版本下载不了, 可能是jitpack的问题!
> 
> 能说这个库真的没有完整教程吗，详细使用wiki。。。

来群里问吧!
