### ISSUE TITLE
有3层折叠，每一级的布局不一样怎么做？

### ISSUE THREAD

**Issue by eegoworld** [angcyo/DslAdapter#33]
![9b23b3be48d8b5e0ec0f54f01f900d0](https://github.com/angcyo/DslAdapter/assets/139188159/5fc5cf47-2d7e-46d8-9d5c-001314b6d97e)
每级显示不同的布局，公司-》部门-》员工

**Comment by angcyo** [comment]
用自定义的`Item`就可以, 逻辑代码不变, 布局没有限制.

**Comment by eegoworld** [comment]
ok   就是每级重新下 Item

![e98112ace082f3aca85bea39f5dfa88](https://github.com/angcyo/DslAdapter/assets/139188159/0f31340c-60e4-4229-b0db-6699008e50ac)
如果要做全选功能，
![image](https://github.com/angcyo/DslAdapter/assets/139188159/aa2307bd-4337-45e9-89a4-e35d40b21bd2)   我要在父亲里面，加个类似这样的变量？

**Comment by angcyo** [comment]
自定义一个`Item`, 基础逻辑复制粘贴, 其它自由发挥.

**Comment by eegoworld** [comment]
嗯  这种DSL 写法突然有点不适应，再研究下

**Comment by eegoworld** [comment]
可以帮忙实现下，请喝奶茶，有偿

**Comment by angcyo** [comment]
你建个`demo`仓.

**Comment by eegoworld** [comment]
https://github.com/eegoworld/3Three.git  这个

**Comment by angcyo** [comment]
你要把`demo`写好啊.

**Comment by eegoworld** [comment]
需求：
1，总共3层或3级
2，每层布局不一样
3，前2层都有全选（反选）功能，不能互相影响

**Comment by eegoworld** [comment]
我思路都没有，demo没法写

**Comment by eegoworld** [comment]
方便加个微信？

**Comment by angcyo** [comment]
对应`demo`已更新, 拉取最新代码即可.

![image](https://github.com/angcyo/DslAdapter/assets/6269676/5782b04e-0271-442a-8a9a-e88435308e5a)
