### ISSUE TITLE
关于布局问题

### ISSUE THREAD

**Issue by qq570026938** [angcyo/DslAdapter#5]
如果一个页面中有轮播，有横向滑动的，有占满一行的，参考腾讯爱奇艺的推荐页，这种的怎么做好呢，是一个recycleview实现还是scrollveiw嵌套实现呢，这个好像不能用这个adapter实现吧

**Comment by angcyo** [comment]
竖向的RV, 嵌套横向的RV.

RV就可以使用这个`DslAdapter`
