### ISSUE TITLE
偶尔会出现数据不显示或者不刷新

### ISSUE THREAD

**Issue by qingweiSun** [angcyo/DslAdapter#6]
dslAdapter.headerItems.clear()
  dslAdapter.headerItems.add(DslAdapterItem())

偶尔出现页面不显示，但是重新刷新就有了

**Comment by qingweiSun** [comment]
还维护吗。蛮喜欢这个库的

**Comment by angcyo** [comment]
> dslAdapter.headerItems.clear()
> dslAdapter.headerItems.add(DslAdapterItem())
> 
> 偶尔出现页面不显示，但是重新刷新就有了

这种方式添加的`Item`, 并不会触发库中的刷新机制.

还需要调用: `com.angcyo.dsladapter.DslAdapter#_updateAdapterItems`和`com.angcyo.dsladapter.DslAdapter#updateItemDepend`这2个方法才行.

或者使用库中提供的操作头部`item`的方式`com.angcyo.dsladapter.DslAdapter#changeHeaderItems`

**Comment by angcyo** [comment]
> 还维护吗。蛮喜欢这个库的

长期维护.

**Comment by qingweiSun** [comment]
好的，谢谢
