### ISSUE TITLE
关于侧滑菜单和长按拖动的问题

### ISSUE THREAD

**Issue by lijinshanmx** [angcyo/DslAdapter#7]
`SwipeMenuHelper.install(this);
DragCallbackHelper.install(this)`
当两者同时开启的时候，左滑出现菜单，但是同时会触发长按的拖动效果。然后松手就可以上下拖动，甚至是左右侧滑菜单的时候就可以上下拖动了，有没有方法调用可以避免这种情况，还是说这两个不能同时设置呀~

**Comment by lijinshanmx** [comment]
应该是左右滑动的时长正好达到了长按LongPress的时长了，导致辨别冲突了。

**Comment by angcyo** [comment]
`2.6.1` 修复了手势冲突.

你需要将`DragCallbackHelper`对象赋值给`SwipeMenuHelper`对象
```
DragCallbackHelper.install(xxx).apply {
    swipeMenuHelper?._dragCallbackHelper = this
}
```

**Comment by lijinshanmx** [comment]
https://user-images.githubusercontent.com/6552340/123366340-a12a6980-d5aa-11eb-8ddc-91e131bb7765.mp4

复现：
4秒 时 慢慢向左滑动，然后拖拽当前ItemView， 菜单收缩，  【正常】

8秒时 向左fling，然后拖拽当前ItemView，会触发上下拖动的问题。 【冲突】

描述:
2.6.1修改手指左右滑动菜单时，上下滚动会触发拖拽的问题，
但是 如果打开菜单时是 fling操作，会触发LongPress效果，导致滑动时触发拖动效果。

**Comment by angcyo** [comment]
https://github.com/angcyo/DslAdapter/issues/9#issuecomment-868184113
