### ISSUE TITLE
侧滑菜单fing动作和长按拖动的问题

### ISSUE THREAD

**Issue by lijinshanmx** [angcyo/DslAdapter#9]
https://user-images.githubusercontent.com/6552340/123366340-a12a6980-d5aa-11eb-8ddc-91e131bb7765.mp4

复现：
4秒 时 慢慢向左滑动，然后拖拽当前ItemView， 菜单收缩，  【正常】

8秒时 向左fling，然后拖拽当前ItemView，会触发上下拖动的问题。 【冲突】

描述:
2.6.1修改手指左右滑动菜单时，上下滚动会触发拖拽的问题，
但是 如果打开菜单时是 fling操作，会触发LongPress效果，导致滑动时触发拖动效果。

_Originally posted by @lijinshanmx in https://github.com/angcyo/DslAdapter/issues/7#issuecomment-868181468_

**Comment by lijinshanmx** [comment]
【小米11为例】如果手机是震动模式的话，当fling菜单以后，会震动一下，触发系统的长按震动效果。以此也可以辨别是触发了长按动作。

**Comment by angcyo** [comment]
`2.6.2`已修复.

这次用了`反射+缓存`的方式取消了`长按事件`的冲突.
